# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vardas', models.CharField(default='', max_length=200)),
                ('Pavarde', models.CharField(default='', max_length=200)),
                ('Miestas', models.CharField(default='', max_length=200)),
                ('Salis', models.CharField(default='', max_length=200)),
                ('pub_date', models.DateTimeField(default='', verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Kita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Telefonas', models.CharField(default='', max_length=200)),
                ('Email', models.CharField(default='', max_length=200)),
                ('Artist', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.Artist')),
            ],
        ),
    ]
