# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20161101_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='Miestas',
            new_name='ArtistName',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='Pavarde',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='Salis',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='Vardas',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='pub_date',
        ),
    ]
