# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20161101_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='Email',
            new_name='AlbumTitle',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='Telefonas',
            new_name='NumberofTracks',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='Artist',
            new_name='RecordingArtistID',
        ),
        migrations.AddField(
            model_name='album',
            name='RecordingLabel',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='album',
            name='YearReleased',
            field=models.CharField(default='', max_length=200),
        ),
    ]
