# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20161101_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumTracks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TrackNumber', models.CharField(default='', max_length=200)),
                ('TrackTitle', models.CharField(default='', max_length=200)),
                ('TrackLenght', models.CharField(default='', max_length=200)),
                ('AlbumID', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.Album')),
            ],
        ),
    ]
