# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_albumtracks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Genre', models.CharField(default='', max_length=200)),
                ('AlbumID', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.Album')),
            ],
        ),
    ]
