# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 21:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_genre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='Albumgenre',
        ),
    ]
