# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20161101_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recorded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateTimeField(verbose_name='date published')),
                ('enddate', models.DateTimeField(verbose_name='date published end')),
                ('AlbumID', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.Album')),
            ],
        ),
    ]
