# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_recorded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recorded',
            name='enddate',
            field=models.DateTimeField(verbose_name='Finished'),
        ),
        migrations.AlterField(
            model_name='recorded',
            name='startdate',
            field=models.DateField(verbose_name='Started'),
        ),
    ]
