# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20161101_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recorded',
            name='enddate',
            field=models.DateField(verbose_name='Finished'),
        ),
    ]
