# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20161101_2345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recorded',
            old_name='enddate',
            new_name='Enddate',
        ),
        migrations.RenameField(
            model_name='recorded',
            old_name='startdate',
            new_name='Startdate',
        ),
    ]
