# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20161101_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recorded',
            name='id',
        ),
        migrations.AlterField(
            model_name='recorded',
            name='AlbumID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='polls.Album'),
        ),
    ]
