# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20161102_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Birthname', models.CharField(default='', max_length=200)),
                ('Instruments', models.CharField(default='', max_length=200)),
                ('Born', models.DateField(verbose_name='Born')),
                ('RecordingArtistID', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.Artist')),
            ],
        ),
    ]
