# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instruments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Instruments', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='members',
            name='Instruments',
        ),
        migrations.AddField(
            model_name='instruments',
            name='member',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.Members'),
        ),
    ]
