# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20161102_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instruments',
            old_name='Instruments',
            new_name='Instrument',
        ),
    ]
