# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 21:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_singles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singles',
            old_name='ArtistID',
            new_name='RecordingArtistID',
        ),
    ]
